{% set name = "conda-vendor" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}
source:
  url: https://github.com/MetroStar/conda-vendor/archive/refs/tags/v{{ version }}.tar.gz
  sha256: f860fcc3c9daadf78a665191d1c233358c2ca429126bd94fe5b365dbec563a4d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - conda-vendor = conda_vendor.__main__:cli

requirements:
  host:
    - pip
    - python >=3.7
    - click
    - conda-build
    - git
  run:
    - python >=3.7
    - conda-lock==1.1.2
    - pydantic=1.8.1
    - pyyaml
    - requests
    - click
    - ruamel.yaml
    - git
    - conda-build
test:
  imports:
    - conda_vendor

about:
  home: https://github.com/MetroStar/conda-vendor
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Conda Vendor is a tool to create local conda channels and manifests for vendored offline deployments

extra:
  recipe-maintainers:
    - jbouder
    - kcpevey
    - iameskild
    - tylerpotts
    - ghoersti
    - rigzba21
