{% set name = "conda-vendor" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}
source:
  url: https://github.com/MetroStar/conda-vendor/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 54aa19ee1196c01989d762c888bf55dd2c5f308bde26ed62880237462173aca1

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - conda-vendor = conda_vendor.__main__:cli

requirements:
  host:
    - pip
    - python >=3.6
    - click
    - conda-build
    - git
  run:
    - python >=3.6
    - conda-lock
    - pyyaml
    - requests
    - click
    - ruamel.yaml
    - conda-build
    - git

test:
  imports:
    - conda_vendor

about:
  home: https://github.com/MetroStar/conda-vendor
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Conda Vendor is a tool to create local conda channels and manifests for vendored offline deployments

extra:
  recipe-maintainers:
    - tylerpotts
    - ghoersti
    - rigzba21
